### ISSUE TITLE
using excelR with images / resizing & shape changing

### ISSUE THREAD

**Issue by pi-at-git** [Swechhya/excelR#103]
Hello! Following you example bringing images into table cells I successfully managed to display SVG images in my excelR table. As a peculiarity, I'm using data URIs because my images are created on the fly generated via base64enc::dataURI(mime = "image/svg+xml", encoding = "base64", tempfile). Works great, but I haven't found a way to resize the images in the cells yet. It appears to me as if the size is fixed to a quadratic shape of certain size (100x100?). Is it possible to increase the size and to change to a rectangular the shape?

**Comment by Swechhya** [comment]
@pi-at-git  you can achieve this by using CSS. Example:

```
library(shiny)
library(excelR)

data <- data.frame(Title = c("Paul Parker", "Mark Ellen"),
                   Cover =  c("https://marketplace.canva.com/MACcZp2p4po/2/0/thumbnail_large/canva-black-white-acoustic-album-cover-MACcZp2p4po.jpg",                          "https://marketplace.canva.com/MACcY55adP4/1/0/thumbnail_large/canva-black-and-white-masculine-acoustic-modern-album-cover-MACcY55adP4.jpg"))

columns <- data.frame(title = colnames(data),
                      type = c("text", "image"),
                      width = c(120, 200))


ui <- fluidPage(
  tags$head(tags$style(
    ".jexcel tbody tr td img {
       width: 200px!important; 
        max-width: 200px !important;
    }"
  )),
  excelOutput("table1")
)

server <- function(input, output, session) {
  
  output$table1 <- renderExcel({
    excelTable(data = data, columns = columns)
  })
  
}

shinyApp(ui, server)
```

**Comment by Swechhya** [comment]
Closing this, feel free to open if this does not answer your question

**Comment by pi-at-git** [comment]
Works great for me! Thanks for the quick response.
