### ISSUE TITLE
Update table from Shiny

### ISSUE THREAD

**Issue by marciz** [Swechhya/excelR#13]
Hi!
Thanks for your excelR package!
I am trying to update table content from Shiny but creates duplicate table rather than replaces existing one.
```
library(shiny)
library(excelR)
shinyApp(
  ui = fluidPage(
    radioButtons(inputId = 'data', label = 'Data', choices = c('iris', 'mtcars')),
    excelOutput("table")
  ),
    server = function(input, output, session) {
    output$table <- renderExcel({
      dt <- get(input$data)
      excelTable(data = dt)
    })
  }
)
```
Output:
![image](https://user-images.githubusercontent.com/5264211/62104456-5a417580-b2a8-11e9-8d93-4ef321c84309.png)

sessionInfo:
> R version 3.6.0 (2019-04-26)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=Latvian_Latvia.1257  LC_CTYPE=Latvian_Latvia.1257   
> [3] LC_MONETARY=Latvian_Latvia.1257 LC_NUMERIC=C                   
> [5] LC_TIME=Latvian_Latvia.1257    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] excelR_0.2.0 shiny_1.3.2 
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.1      digest_0.6.18   later_0.8.0     mime_0.6        R6_2.4.0       
>  [6] xtable_1.8-4    jsonlite_1.6    magrittr_1.5    rlang_0.3.4     promises_1.0.1 
> [11] tools_3.6.0     htmlwidgets_1.3 httpuv_1.5.1    yaml_2.2.0      compiler_3.6.0 
> [16] htmltools_0.3.6

**Comment by Swechhya** [comment]
Thank you @marciz for reposting the issue. You can download the development version of the package that resolves this issue.

**Comment by marciz** [comment]
Thanks @Swechhya , it works now
Ultimately I am trying to create table with calculated variable
```
library(shiny)
library(excelR)
dt <- iris
dt$mysum <- dt$Sepal.Length + dt$Sepal.Width
shinyApp(
  ui = fluidPage(
    excelOutput("table")
  ),
    server = function(input, output, session) {
    rv <- reactiveValues(
      dt = dt
    )
    output$table <- renderExcel(excelTable(data = rv$dt))
    observeEvent(input$table,{
      dt <- excel_to_R(input$table)
      dt$mysum <- dt$Sepal.Length + dt$Sepal.Width
      rv$dt <- dt
    })
  }
)
```
It works as expected, just small inconvenience from user perspective is that cells selection is lost when table updates (due to new jexcel)

**Comment by Swechhya** [comment]
Yes, @marciz I can see that could be the inconvenience from user perspective. You can create a new issue for that and I'll try to find a better solution to table updation than currently implemented.
