### ISSUE TITLE
Feature Request: Column types based on data.frame

### ISSUE THREAD

**Issue by marciz** [Swechhya/excelR#17]
Would it be reasonable to add column type mapping in excelTable if param columns$type is missing?
Something like in rhandsontable https://github.com/jrowen/rhandsontable/blob/639b0a511b216391df44c45ea7ef8c934269c28a/R/rhandsontable.R#L69

**Comment by Swechhya** [comment]
Thanks @marciz. It is definitely something that could be worked upon.

**Comment by Swechhya** [comment]
@marciz, This feature has been added in the latest development build.
