### ISSUE TITLE
Update table column name after rename in Shiny?

### ISSUE THREAD

**Issue by rpodcast** [Swechhya/excelR#19]
I'm very excited to see this package, so thank you for creating this!  One key advantage I see over `rhandsontable` right away is the ability to rename the column when right-clicking.  While adding/removing rows or columns can be registered in a Shiny app, I noticed that after renaming the column that the data frame is still having the old column name afterwards.  Below is a simple reprex that shows the issue.  Happy to help provide more debugging output if it helps.

```r
library(shiny)
library(excelR)

shinyApp(
  ui = fluidPage(excelOutput("table"), verbatimTextOutput("out")),
  server = function(input, output, session) {

    values = reactiveValues()
    
    data = reactive({
      if (!is.null(input$table)) {
        tmp <- input$table
        DF = excel_to_R(input$table)
      } else {
        if (is.null(values[["DF"]]))
          DF = iris[1:10,]
        else
          DF = values[["DF"]]
      }
      
      values[["DF"]] = DF
      DF
    })
    
    
    output$table <- renderExcel({
      DF = data()
      if (!is.null(DF)) {
        excelTable(DF)
      }
    })
    
    output$out <- renderPrint({
      data()
    })
  }
)
```

**Comment by Swechhya** [comment]
Thank you reporting the issue. It has been resolved in the latest development version.

**Comment by rpodcast** [comment]
Terrific!  I just tried it out and works perfectly 👍

**Comment by sonksen** [comment]
Similar to what @rpodcast has said, I really enjoy using this package, its much smoother than some other alternatives I've seen.  But I have noticed that in the above example @rpodcast gave, if you add a new column not at the end of the table, the column names keep the same order but with an NA at the end (rather then in the new column).  See below: 
![image](https://user-images.githubusercontent.com/14075915/68900346-a4d4e980-0701-11ea-9466-e6e3c9e09f07.png)


I'm also happy to help debugging as we really like using this package.

**Comment by Swechhya** [comment]
@sonksen Thank you for reporting this issue. PR for this or any other issue is always welcomed 🙂
