### ISSUE TITLE
comma missing in shiny example on demo page

### ISSUE THREAD

**Issue by brouwern** [Swechhya/excelR#2]
code is currently:

shinyApp(
     ui = fluidPage(excelOutput("table"))
     server = function(input, output, session) {
       output$table <-
      renderExcel(excelTable(data = head(iris)))
      }
    )

comma needed after "ui <- fluidPage(excelOutput("table")),"
eg

shinyApp(
     ui = fluidPage(excelOutput("table")) , 
     server = function(input, output, session) {
       output$table <-
      renderExcel(excelTable(data = head(iris)))
      }
    )

**Comment by Swechhya** [comment]
@brouwern Thanks for reporting the issue. I will surely update the demo page
