### ISSUE TITLE
Date & character column to factor after editing

### ISSUE THREAD

**Issue by marciz** [Swechhya/excelR#25]
**Describe the bug**
Date and character columns are converted to factor after editing any cell

**To Reproduce**
```
library(shiny)
library(excelR)

dt <- iris[1:10,]
dt$Species <- as.character(dt$Species)
dt$date <- Sys.Date()

shinyApp(
  ui = fluidPage(excelOutput("table")),
  server = function(input, output, session) {
    rv <- reactiveValues(
      dt = dt
    )
    output$table <- renderExcel(
      excelTable(data = rv$dt, autoColTypes = TRUE)
    )
    observeEvent(input$table,{
      str(rv$dt)
      xls <- excel_to_R(input$table)
      rv$dt <- xls
      str(rv$dt)
    })
  }
)
```

> 'data.frame':	10 obs. of  6 variables:
>  $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9
>  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1
>  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5
>  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1
>  $ Species     : chr  "setosa" "setosa" "setosa" "setosa" ...
>  $ date        : Date, format: "2019-09-17" "2019-09-17" "2019-09-17" ...
> 'data.frame':	10 obs. of  6 variables:
>  $ Sepal.Length: num  1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9
>  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1
>  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5
>  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1
>  $ Species     : Factor w/ 1 level "setosa": 1 1 1 1 1 1 1 1 1 1
>  $ date        : Factor w/ 1 level "2019-09-17": 1 1 1 1 1 1 1 1 1 1

**Desktop (please complete the following information):**
> R version 3.6.1 (2019-07-05)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 17763)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=Latvian_Latvia.1257  LC_CTYPE=Latvian_Latvia.1257   
> [3] LC_MONETARY=Latvian_Latvia.1257 LC_NUMERIC=C                   
> [5] LC_TIME=Latvian_Latvia.1257    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] excelR_0.3.0 shiny_1.3.2 
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.2       digest_0.6.20    later_0.8.0      mime_0.7         R6_2.4.0        
>  [6] xtable_1.8-4     jsonlite_1.6     magrittr_1.5     rlang_0.4.0      promises_1.0.1  
> [11] tools_3.6.1      htmlwidgets_1.3  httpuv_1.5.1     yaml_2.2.0       rsconnect_0.8.15
> [16] compiler_3.6.1   htmltools_0.3.6

**Comment by Swechhya** [comment]
Thank you for reporting the issue. This clearly has been an oversight on my part. 
In case of date it is easily identifiable as `calendar` type in js so can be easily set as date while converting back. 
In case of factors and characters both will of `text` type in the js side so converting it back is a little tricky. Either it will always be converted to character or always converted to factor. So this will have to be managed in a better way. What kind of output do you expect?

**Comment by marciz** [comment]
Hi, I think character would be preferable 
If original data has any factor field there might be warning that it would be converted to character after edits
Or if want to get more complex we could add extra parameter in function stringsAsFactors = TRUE/FALSE

**Comment by Swechhya** [comment]
I guess `stringAsFactors = TRUE/FALSE` would make it more predictable. Another option would be changing the factors into dropdown instead of just plain text with `autoColTypes`, which would make it more predictable and also be useful I to create dropdowns I guess.

**Comment by marciz** [comment]
Yes, this could also be solution for type mapping:
 factor <-> dropdown
 character <-> text
I think it is something similar in rhandsontable

**Comment by Swechhya** [comment]
@marciz This has been fixed in the latest development version.
