### ISSUE TITLE
rewrite in es5 JavaScript to work in older RStudio

### ISSUE THREAD

**Issue by timelyportfolio** [Swechhya/excelR#3]
Great work, I saw `jExcel` and hoped someone would make it into an `htmlwidget`.  I hope you don't mind me barging in without any permission, but I couldn't find any way to contact you.

RStudio viewer did not become modern until very recently, which means many users of older versions of RStudio will not be able to use `excelR`.

I will submit a pull rewriting JavaScript in ancient form :)

If you agree this is a good thing, then please review that I didn't miss anything.  The only real question I had was on `style`.  I could not find this argument listed in the `jExcel` [docs](https://bossanova.uk/jexcel/v2/docs/quick-reference) so I could not test.

Thanks!!!!

**Comment by Swechhya** [comment]
@timelyportfolio  I certainly agree with you on this. I did not realize that it was only recently that RStudio viewer started using es6. Also, the package uses jexcel [v3](https://bossanova.uk/jexcel/v3/docs/getting-started) and not v2 and table styling has been documented [here](https://bossanova.uk/jexcel/v3/examples/table-style). Thank you for the pull request.
