### ISSUE TITLE
Issue with development version

### ISSUE THREAD

**Issue by marciz** [Swechhya/excelR#31]
**To Reproduce**
```
dt <- data.frame(
  a = rep(c(1, NA), 3),
  b = as.character(rep(c(1, NA), 3)),
  c = as.factor(rep(c(1, NA), 3))
)
dt1 <- excelR::excelTable(
  data = dt
)
dt1
```
![dt1](https://user-images.githubusercontent.com/5264211/65942285-a0948b80-e435-11e9-849e-67a0a855abda.PNG)
```
dt2 <- excelR::excelTable(
  data = dt, 
  columns = data.frame(
    type = excelR:::get_col_types(dt)
  )
)
dt2
```
![dt2](https://user-images.githubusercontent.com/5264211/65942294-a8ecc680-e435-11e9-8f97-ee5b0f3c0aaa.PNG)
`all.equal(dt1, dt2)`
> [1] "Component “x”: Component “colHeaders”: Lengths: 3, 1"                                  
> [2] "Component “x”: Component “colHeaders”: Attributes: < target is NULL, current is list >"
> [3] "Component “x”: Component “colHeaders”: target is character, current is json"           
> [4] "Component “x”: Component “columns”: 1 string mismatch"

**Comment by marciz** [comment]
Nulls in dropdown source might be the issue

`dt1$x$columns`
> [{"type":"numeric","source":[0]},{"type":"dropdown","source":["1",null]},{"type":"dropdown","source":["1",null]}] 

`dt2$x$columns`
> [{"type":"numeric"},{"type":"dropdown"},{"type":"dropdown"}]

**Comment by Swechhya** [comment]
@marciz Thank you for reporting the issue. Will start working on it right away.

**Comment by marciz** [comment]
It think you can try to change get_col_types.r line https://github.com/Swechhya/excelR/blob/97e241bfd8fd3b8ad5cc87a688dbc393496f44f8/R/get_col_types.R#L40
to
`levels(data[,col])`

**Comment by Swechhya** [comment]
This resolves the issue for the given case partially but when there is only one unique value it will still fail.

**Comment by marciz** [comment]
Yes, drop-downs doesn't work properly when only single factor:
Works:
```
excelR::excelTable(
  data =  data.frame(
    a = rep(c(1, NA), 3),
    b = as.character(rep(c(1, NA), 3)),
    c = as.factor(rep(c(1, 2, NA), 2))
  )
)
```
Doesn't work:
```
excelR::excelTable(
  data =  data.frame(
    a = rep(c(1, NA), 3),
    b = as.character(rep(c(1, NA), 3))
  )
)
```

**Comment by Swechhya** [comment]
With is fix it should be working. Thank you for all the help.
