### ISSUE TITLE
Shiny lost colnames & numeric to factor after edit

### ISSUE THREAD

**Issue by marciz** [Swechhya/excelR#35]
Describe the bug
After shiny table edit (e.g. put char 'a' into Sepal.Length):
* lost colnames when column param used (no issue if columns = NULL)
* if character value input into numeric, column is converted to factor

To Reproduce

```
library(shiny)
library(excelR)

dt <- iris[1:10,]
dt$Species <- as.character(dt$Species)
dt$date <- Sys.Date()

shinyApp(
  ui = fluidPage(excelOutput("table")),
  server = function(input, output, session) {
    rv <- reactiveValues(
      dt = dt
    )
    output$table <- renderExcel(
      excelTable(data = rv$dt, 
                 columns = data.frame(
                   title = colnames(rv$dt),
                   type = excelR:::get_col_types(rv$dt)
                 ))
    )
    observeEvent(input$table,{
      str(rv$dt)
      xls <- excel_to_R(input$table)
      rv$dt <- xls
      str(rv$dt)
    })
  }
)
```
> 'data.frame':	10 obs. of  6 variables:
>  $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9
>  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1
>  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5
>  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1
>  $ Species     : chr  "setosa" "setosa" "setosa" "setosa" ...
>  $ date        : Date, format: "2019-10-02" "2019-10-02" "2019-10-02" ...
> 'data.frame':	10 obs. of  6 variables:
>  $ : Factor w/ 7 levels "4.4","4.6","4.7",..: 7 4 3 2 5 6 2 5 1 4
>  $ : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1
>  $ : num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5
>  $ : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1
>  $ : chr  "setosa" "setosa" "setosa" "setosa" ...
>  $ : Date, format: "2019-10-02" "2019-10-02" "2019-10-02" ...

> other attached packages:
> [1] excelR_0.3.1 shiny_1.3.2 

Is there a way to limit character input into numeric column? So that only numeric values are accepted. Date columns already don't allow character input

**Comment by marciz** [comment]
To avoid character input in numeric fields, probably need to add mask parameter to column data.frame. If it is numeric then it might be `mask:'#.#'` by default

**Comment by Swechhya** [comment]
@marciz Thank you for reporting the issue. I'll look into the issue of why column names are getting lost after edit. and why the numeric value is getting converted to factor instead of character. Should be related to  one of the recent changes made in `excel_to_R` function.

I'll see if `jexcel` provides an extension to restrict the number/character input into columns. Could you file a new feature request for this so that I can work on it in the upcoming version?

**Comment by Swechhya** [comment]
@marciz, the above two PR should resolve the issues you have reported. You can reopen this if the issue you have reported hasn't been addressed in latest development version.
