### ISSUE TITLE
Restrict the number/character input

### ISSUE THREAD

**Issue by marciz** [Swechhya/excelR#36]
Possible solution is to add mask options in column data.frame
```
dt <- data.frame(
  a = 1:5,
  b = NA,
  c = NA
  )
excelR::excelTable(
  data = dt,
  columns = data.frame(
    title = c('a', 'b', 'c'),
    type = c('integer', 'numeric', 'numeric'),
    mask = c('#', '#.#', '')
  )
)
```

There are some open issues with masks 
https://github.com/paulhodel/jexcel/issues/630
https://github.com/paulhodel/jsuites/issues/14

**Comment by Swechhya** [comment]
@marciz, your PR #45 resolves this issue, so closing this.
