### ISSUE TITLE
More flexible columns data.frame in excelTable

### ISSUE THREAD

**Issue by marciz** [Swechhya/excelR#37]
Can we make columns data.frame in excelTable more flexible by removing
https://github.com/Swechhya/excelR/blob/5b3fbbb790f40b188bf5eeb2554b6a4c037c9ad9/R/jexcel.R#L182
https://github.com/Swechhya/excelR/blob/5b3fbbb790f40b188bf5eeb2554b6a4c037c9ad9/R/jexcel.R#L192
There are other possible parameters users might find useful - decimal, align, wordWrap,.. Not sure it is useful to try to mention all of them in jexcel.R code
Probably only 'title' column would be required, some others might be listed in documentation/examples

**Comment by Swechhya** [comment]
**Requirement:**
1. Remove column name  checking for `column` parameter  in `excelTable` function.
2. Instead add the example for different parameters that could be used in the documentation.

**Comment by Swechhya** [comment]
@marciz , closing this issue as your PR #45 has handled this.
