### ISSUE TITLE
remove date format check

### ISSUE THREAD

**Issue by Ranlod** [Swechhya/excelR#43]
Can you remove check on date format? Because jexcel supported more different format date. For Example 'DD.MM.YYYY', 'MM.DD.YYYY', 'YYYY.MM.DD' and other kind formats.
https://github.com/Swechhya/excelR/blob/a9fdb9b03d03a7d984feaa31af1a7fb081fb3e7b/R/jexcel.R#L419

**Comment by Swechhya** [comment]
@Ranlod, we could add other date formats supported by jexcel. This check is there to ensure that user gets a proper warning in case of improper date format.

**Comment by Ranlod** [comment]
@Swechhya ok, but i think it is will not enough flexible resolve

**Comment by marciz** [comment]
Related to #37 , date format is columns parameter `options: { format:'DD/MM/YYYY' }` (https://bossanova.uk/jexcel/v3/examples/date-and-datetime-picker)

**Comment by Swechhya** [comment]
@marciz Although your PR #45 somewhat tries to handle this,  PR to add additional valid date format is more than welcome 😃

**Comment by Swechhya** [comment]
Thanks @Ranlod  for raising the issue, after looking through the different date formats supported, adding valid date formats did not seem flexible. Hence removing the check.
