### ISSUE TITLE
Selected row callback

### ISSUE THREAD

**Issue by GoodMorgon** [Swechhya/excelR#49]
Many thanks (again) for developing this package!

Using the package with  `shiny` it would be awsome if the possibility to easily retrieve the selected row for an `excelTable()` object could be implemented. This is needed for example if a graph should be updated depending on the row chosen in the table.

I can see from using the Inspector in Google Chrome that the class of `<td>` and `<tr>` inside the jexcel changes to "selected" when switching rows/cells, but my knowledge of JavaScript is too poor to make any use of it...

**Comment by Swechhya** [comment]
@GoodMorgon  Thank you for suggesting this much needed feature.

New function `get_selected_data` has been added to get the selected cells in excel table. You can refer to [this example](https://swechhya.github.io/excelR/#getting-selected-data-in-shiny-currently-only-available-in-development-version) for more details. Please note that this function is currently available in development version only.
