### ISSUE TITLE
changed behaviour of excel_to_R() function

### ISSUE THREAD

**Issue by GoodMorgon** [Swechhya/excelR#53]
Thank you for the super fast response on the last feature request!

Downloading the dev (github) version I noticed that the `excel_to_R()` function now behaves differently than from the latest cran release.

Instead of returning the full excel table it now only returns the changes for the edited cell. Is this an intended behaviour or a bug (I did not find it under the changelog)?

The current behaviour makes it almost impossible to extract the actual changes made by a user (as you don't know which row or column was edited by the callback).

The current (unintended?) behaviour can be seen from the example at https://swechhya.github.io/excelR/index.html

```
  library(shiny)
  library(excelR)

   shinyApp(
     ui = fluidPage(excelOutput("table")),
     server = function(input, output, session) {
       output$table <-
      renderExcel(excelTable(data = head(iris)))
      observeEvent(input$table,{
        print(excel_to_R(input$table))
      })
      }
    )
```

**Comment by Swechhya** [comment]
@GoodMorgon  Thank you for reporting the issue. This was a side effect of adding `get_selected_data` function. The `input$table` is always triggered regardless   the value is changed or selected. When the value is changed in the table `excel_to_R(input$table)` would now give the entire table while upon selection it would give `NULL` as there is no change in the table.

**Comment by marciz** [comment]
@Swechhya I think it is still breaking change in modified example
```
library(shiny)
library(excelR)
shinyApp(
  ui = fluidPage(excelOutput("table")),
  server = function(input, output, session) {
    rv <- reactiveValues(
      dt =  head(iris)
    )
    output$table <- renderExcel(excelTable(data = rv$dt))
    observeEvent(input$table,{
      rv$dt <- excel_to_R(input$table)
    })
  }
)
```
Also, is it possible to turn off trigger for selection change if it is not necessary? I guess this might slow down & cause issues in shiny

**Comment by Swechhya** [comment]
@marciz I agree with you on that, we could add a parameter in `excelTable` to specify if we want to get selected values and based on that we could turn on the trigger for selection. Also, with the current changes in this version you might want to check for `NULL` before printing the table. Code will be something like this:

```library(shiny)
library(excelR)
shinyApp(
  ui = fluidPage(excelOutput("table")),
  server = function(input, output, session) {
    rv <- reactiveValues(
      dt =  head(iris)
    )
    output$table <- renderExcel(excelTable(data = rv$dt))
    observeEvent(input$table,{
      table_val <- excel_to_R(input$table)
      if(!is.null(table_val)){
        rv$dt <- table_val
      }
     
    })
  }
)
```
What do you think about this approach? We have to do this because we use `Shiny.setInputValue`  for both `excel_to_R` and `get_selected_data`.

As for turning off trigger for selection change I'll add `getSelectedData` parameter in `excelTable` function which on default would be `FALSE`.

**Comment by marciz** [comment]
@Swechhya, I agree - parameter `getSelectedData `sounds good. 
I haven't looked at recent changes in details, but what if `getSelectedData = TRUE` and I need to change the input data? Possible solution would be `excel_to_R ` to return something like `list(data = ..., selectedData = ...)`

**Comment by Swechhya** [comment]
@GoodMorgon  @marciz  the issue mentioned in this PR has been fixed in the latest development version. The `excel_to_R` behaviour is as in the earlier versions. Feel free to open it if you think the issue still persists.
