### ISSUE TITLE
add selected row and column ids to get_selecetd_data()

### ISSUE THREAD

**Issue by GoodMorgon** [Swechhya/excelR#54]
Hello again! 

If the row and column numbers of the selected data that is available through `get_selected_data()` could be made available this would be awsome. 

Currently there is no way for a script to know exactly which columns / rows to directly filter the selected data on, as the row and column ids of the selected data is not returned. 

This greatly limits the function's capabilities as a "filter & select" tool, as one has to know which column the `get_selected_data` represents beforehand or do a risky compare of the data.

**Comment by Swechhya** [comment]
@GoodMorgan how do you suggest the row and column number should appear? Any reference to this would be helpful in adding this enhancement and release it in next few days.

**Comment by Swechhya** [comment]
@GoodMorgon  In the latest development version I have added a function `get_selected_data_boundary` which will give you the boundary of selected cells. Hope that this helps!
