### ISSUE TITLE
Multiple dropdown

### ISSUE THREAD

**Issue by marciz** [Swechhya/excelR#58]
**Describe the bug**
Multiple dropdown not working, not able to select any value

**To Reproduce**
```
library(excelR)
data = data.frame( Make = c('Honda', 'Honda', 'Hyundai'), 
                   Car = c('Civic', 'City', 'Polo'))
columns = data.frame(title=c('Make', 'Car'),
                     width= c(300, 300),
                     type=c('text', 'dropdown'),
                     multiple=c(NA, TRUE),
                     source=I(list(0,c('Civic', 'City',  'Polo', 'Creta', 'Santro'))))
excelTable(data=data, columns = columns)
```

**Desktop (please complete the following information):**
> R version 3.6.1 (2019-07-05)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 18362)
> 
> Matrix products: default
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] excelR_0.3.1
> 
> loaded via a namespace (and not attached):
> [1] htmlwidgets_1.5.1 compiler_3.6.1    htmltools_0.4.0   tools_3.6.1       yaml_2.2.0       
> [6] Rcpp_1.0.2        jsonlite_1.6      digest_0.6.21     rlang_0.4.0

**Comment by Swechhya** [comment]
Closing this issue as PR #61 fixes this. 

@marciz  Feel free to reponen it if the latest development version does not resolve the issue.
