### ISSUE TITLE
excelR table in Shiny not visible in IE11

### ISSUE THREAD

**Issue by fmarois** [Swechhya/excelR#68]
Hello,
when trying to view a shiny app using excelR in Internet explorer 11 the table does not show up.
Upon investigation the error code provided by IE is this
`SCRIPT1014: Incorrect character
jexcel.js (54,50)`
I think the problematic character is a backquote.
My app is running in a shiny server and I am running excelR version 0.4.0.
Thank you for your great work, I really appreciate it.

**Comment by Swechhya** [comment]
@fmarois  Can you please share the code to replicate the issue?

**Comment by fmarois** [comment]
Here you go:
When I try to run this in Internet Explorer the excelOutput does not get displayed.

`library(excelR)

ui <- navbarPage("Cars Page",
                 theme = "bootstrap.min.css",
                 tabPanel("cars",
                          mainPanel(
                            fluidRow(excelOutput(outputId = "cars")
                            )
                            
                          )
                 )
)


server <- function(input, output,session) {
  
  eTable <- reactive({ 
    excelTable(
      data=mtcars,autoFill=TRUE, autoWidth=FALSE)
  })
  
  output$cars <- renderExcel(
    eTable()
  )
  
  raw_bedsMod<- eventReactive(input$cars,{
    table_data <- excel_to_R(input$cars)
    if(!is.null(table_data)){
      return(table_data)
    }
  })  
}


shinyApp(ui = ui, server = server)
`
Thank you for looking into this.

**Comment by Swechhya** [comment]
The support for IE 11 has been added in PR #69 and should be available in the latest development version. Feel reopen this if the issue you have reported hasn't been addressed in latest development version.
