### ISSUE TITLE
add communication with Shiny

### ISSUE THREAD

**Issue by timelyportfolio** [Swechhya/excelR#7]
`excelR` renders great with Shiny, but since it allows changes in the table, it would be great to capture those changes in R similar to `rhansontable`.  Fortunately, `jExcel` fires events when changes are made, but unfortunately without tranformation the objects on the JavaScript side the values are passed as a `vector`.

I put a quick example together below.

```
library(shiny)
library(excelR)

ui <- excelOutput("excel")

server <- function(input, output, session) {
  output$excel <- renderExcel({
    excel <- excelTable(matrix(1:100, ncol=10))
    excel$x$onchange <- htmlwidgets::JS(
"
function(obj,cell,value) {
  debugger
  if(HTMLWidgets.shinyMode) {
    Shiny.setInputValue(obj.id, this.data)
  }
}
"
    )
    excel
  })
  
  observeEvent(input$excel, {
    print(input$excel)
  })
}

shinyApp(ui,server)
```

I am happy to work on this, but I wanted to make sure you agreed with the idea.  Thanks!

**Comment by Swechhya** [comment]
I do agree with you on this. I am certainly willing to accept pull request on this.
