### ISSUE TITLE
excel_to_R throws an error when a column is deleted in the "Reading changed data from excel table in Shiny" example

### ISSUE THREAD

**Issue by bppipher** [Swechhya/excelR#71]
In the "Reading changed data from excel table in Shiny" found [here](https://swechhya.github.io/excelR/#reading-changed-data-from-excel-table-in-shiny) if you load this and delete any column it throws an error

`Warning: Error in <-: 'names' attribute [5] must be the same length as the vector [4]`

`  74: colnames<-`

`  73: excel_to_R`

`  72: observeEventHandler [C:\myfilepath]`

`   1: runApp`

**Comment by Swechhya** [comment]
@bppipher Can you provide the excelR version that has this issue?

**Comment by Swechhya** [comment]
@bppipher This bug has been fixed in the latest development version. Feel free to reopen the issue if the bug persists.
