### ISSUE TITLE
Column insertion resulted in mismatched header and data

### ISSUE THREAD

**Issue by wyu** [Swechhya/excelR#76]
**Describe the bug**
Upon the insertion of a column, the output of "excel_to_R call" in a Shiny app yields an invalid data frame where the inserted col is missing from the colHeader

**To Reproduce**
Using the sample app

library(shiny)
library(excelR)

shinyApp(
  ui = fluidPage(excelOutput("table")),
  server = function(input, output, session) {
    output$table <-
      renderExcel(excelTable(data = head(iris)))
    observeEvent(input$table,{
      table_data <- excel_to_R(input$table)
      if(!is.null(table_data)){
        print(table_data)
      }
    })
  }
)
**Expected behavior**
After the insertion of a new column, the data table should look like the screen shot below.

<img width="501" alt="Screen Shot 2020-07-24 at 3 31 30 PM" src="https://user-images.githubusercontent.com/760649/88429891-785f8a00-cdc5-11ea-9e19-8929af8145ba.png">

However, the data frame is invalid since the new column was added to the end of the colHeaders, while the body is properly ordered.

 Sepal.Width Petal.Length Petal.Width Species     NA
1          5.1                      3.5         1.4     0.2 setosa
2          4.9                      3.0         1.4     0.2 setosa
3          4.7                      3.2         1.3     0.2 setosa
4          4.6                      3.1         1.5     0.2 setosa
5          5.0                      3.6         1.4     0.2 setosa
6          5.4                      3.9         1.7     0.4 setosa

**Comment by wyu** [comment]
Actually this issue was reported in another thread toward the end of the discussion:
https://github.com/Swechhya/excelR/issues/19

Is there any resolution to this problem?

Thanks!

**Comment by Swechhya** [comment]
@wyu Thank you for reporting the issue. I'll start looking into resolution right away.

**Comment by Swechhya** [comment]
@wyu This issue has now be resolved in the latest development version. Feel reopen the issue if the issue persists.

**Comment by HumanRickshaw** [comment]
> I enjoy using this package but inserting columns and renaming columns is still problematic.  I am experiencing this exact issue.
