### ISSUE TITLE
Single column data.frames have wrong column name

### ISSUE THREAD

**Issue by mmoisse** [Swechhya/excelR#80]
**Describe the bug**
When you provide a data.frame to excelTable with only one column the column name is set to the first letter of that column instead of the full name.

**To Reproduce**

```
library(excelR)
excelTable(datasets::iris[1:10,1,drop=F])
```

**Expected behavior**
The full column name

**Desktop (please complete the following information):**
 - OS: Linux
 - Version excelR_0.4.0 shiny_1.5.0

**Comment by Swechhya** [comment]
Thank you for reporting the issue @mmoisse. This issue has been fixed in #82 and is now available in the development version. Feel free to open it if the issue persists.
