### ISSUE TITLE
Using columns and getSelectedData options in excelTable give unexpecte behaviour with column rename

### ISSUE THREAD

**Issue by mmoisse** [Swechhya/excelR#81]
**Describe the bug**
Defining columns and setting getSelectedData to TRUE in excelTable give unexpected behaviour with column rename. Only the last column name change is remembered.

**To Reproduce**
```
library(shiny)
library(excelR)

shinyApp(
  ui = fluidPage(excelOutput("table"), verbatimTextOutput("out")),
  server = function(input, output, session) {

    data = reactive({
      iris[1:10,]
    })
        
    output$table <- renderExcel({
      DF = data()
      if (!is.null(DF)) {
        excelTable(DF, columns=data.frame(title=colnames(DF)), getSelectedData=T)
      }
    })
    
    output$out <- renderPrint({
      if(!is.null(input$table)) {
         excel_to_R(input$table)
      } else {
         data()
      }
    })
  }
)
```

**Expected behavior**
Persistent column name change

**Desktop (please complete the following information):**
 - OS: Linux
 - Version excelR_0.4.0 shiny_1.5.0

**Comment by Swechhya** [comment]
@mmoisse Thank you for reporting this issue. This has now been fixed in the latest development version. Feel free to reopen this issue if it persists.
