### ISSUE TITLE
Merged Cells not working properly

### ISSUE THREAD

**Issue by shitaka23** [Swechhya/excelR#87]
Hi,

I am using mergedCells as per the code below, however when I run the app the merged cells pushes all values to the right in all rows with the exception of the 1st merged row (See screenshot attached).
 
library(excelR)
library(shiny)

data = data.frame( Make = c('Honda', 'Honda', 'Hyundai'),
                   Car = c('Civic', 'City', 'Creta'),
                   Year = c('2018','2019','2020'))

columns = data.frame(title=c('Make', 'Car','Year'))

# Define UI ----
ui <- fluidPage(
  excelTable(data=data, columns = columns,  mergeCells = list(A1=c(1,2)))  
)

# Define server logic ----
server <- function(input, output) {
  
}

# Run the app ----
shinyApp(ui = ui, server = server)

**Comment by Swechhya** [comment]
Thank you @shitaka23 for reporting this issue. This issue has been addressed in #88 and should be working in the latest development version.

Closing this issue, feel free to open it if again if the issue persists.
