### ISSUE TITLE
 autofill = FALSE does not work?

### ISSUE THREAD

**Issue by daeyoonlee** [Swechhya/excelR#92]
**Describe the bug**
I want to copy all the numbers to the same value, but I don't know how.
Even with autofill = FALSE, if you grab the dot at the bottom right and lower it, the value will automatically increase.

![image](https://user-images.githubusercontent.com/68131229/124351968-78544500-dc38-11eb-8fbf-9aec09917b18.png)

**To Reproduce**

library(excelR)

data = data.frame(Model = c(10,"","",""),
                  Date=c('2006-01-01', '2005-01-01','2004-01-01', '2003-01-01' ),
                  Availability = c(TRUE, FALSE, TRUE, TRUE))

columns = data.frame(title=c('Model', 'Date', 'Availability'),
                     width= c(300, 300, 300),
                     type=c('text', 'calendar', 'checkbox')) 

excelTable(data=data, autoFill = FALSE, columns = columns)

**Expected behavior**
If autofill = FALSE, no auto increment.

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser : chrome
 - Version latest version

**Comment by Swechhya** [comment]
@daeyoonlee  You need to set the `autoIncrement` parameter to `FALSE`. The `excelTable` function would look like this:
`excelTable(data=data, autoFill = FALSE, columns = columns, autoIncrement = FALSE)`

Closing this issue, feel free to open it again if this does not resolve your issue.
