### ISSUE TITLE
Remove Row Index from excelTable? 

### ISSUE THREAD

**Issue by aeynaud** [Swechhya/excelR#98]
I would love to see a way to remove the row index, for style purposes. 
Can this be done using CSS alternatively? 

Thank you for this great package!

**Comment by Swechhya** [comment]
@aeynaud  Yes, this is achievable with CSS.  Example:
```
library(shiny)
library(excelR)

shinyApp(
  ui = fluidPage(
    tags$head(tags$style("
  .jexcel_selectall {
      display: none
    }

  .jexcel_row {
    display: none
  }

  colgroup>col:last-child {
    width:0;
  }")),
    excelOutput("table")
    ),
  server = function(input, output, session) {
    output$table <-
      renderExcel(excelTable(data = head(iris)))
  }
)
```

**Comment by Swechhya** [comment]
@aeynaud Closing this, feel free to open it if this does not answer your question

**Comment by pi-at-git** [comment]
@Swechhya This has an unwanted side effect on setting the column width (intended here: big, small, big, small, big):
![Unbenannt1](https://user-images.githubusercontent.com/66769433/150934617-e9900493-eaa8-43fd-9127-4a10892e3e0b.png)

```
library(shiny)
library(excelR)

shinyApp(
  ui = fluidPage(

    tags$head(tags$style(".jexcel_selectall { display: none }
                          .jexcel_row { display: none }
                          colgroup>col:last-child { width:0; }")),
    excelOutput("table")
    ),

  server = function(input, output, session) {
    output$table <- renderExcel({

       columns <- data.frame(width = c(200,100,200,100,200))

       excelTable(data = head(iris),
                  columns = columns
        )
   })

  }
)

```
observed: small, big, small, big, small

![Unbenannt](https://user-images.githubusercontent.com/66769433/150934184-4213855b-7c3d-42cd-910f-c727464fa4d6.png)

Plus: the width of the first column cannot be changed,  `columns <- data.frame(width = c(600,100,200,100,200))` does not have an effect on column 1 (Sepal.Length) but changes the width of column 2 (Sepal.Width)
